profile:
  m3fc_position: core
  accel_axis: z
  ignition_accel: 25
  burnout_timeout: 7.5
  apogee_timeout: 35
  main_altitude: 300
  main_timeout: 265
  land_timeout: 600

pyros:
  pyro1: none
  pyro2: none
  pyro3: none
  pyro4: none
  pyro5:
    usage: dartsep
    type: metron
    current: 1A
  pyro6:
    usage: drogue
    type: metron
    current: 3A
  pyro7:
    usage: main
    type: metron
    current: 1A
  pyro8: none

accel_cal_x:
  scale: 0.0039
  offset: -4

accel_cal_y:
  scale: 0.0039
  offset: -4

accel_cal_z:
  scale: 0.003984
  offset: -23.63

radio_freq: 869600000
