profile:
  m3fc_position: dart
  accel_axis: z
  ignition_accel: 25
  burnout_timeout: 7.5
  apogee_timeout: 45
  main_altitude: 300
  main_timeout: 295
  land_timeout: 600

pyros:
  pyro1: none
  pyro2: none
  pyro3: none
  pyro4: none
  pyro5:
    usage: drogue
    type: ematch
    current: 1A
  pyro6:
    usage: main
    type: talon
    current: 1A
  pyro7: none
  pyro8: none

accel_cal_x:
  scale: 0.0039
  offset: 7

accel_cal_y:
  scale: 0.0039
  offset: 2

accel_cal_z:
  scale: 0.00395442
  offset: -26.4338

radio_freq: 869500000
